test_that("theme_map", {
  expect_is(default <- theme_map(), "theme")
  expect_is(default, "gg")
  expect_equivalent(default$axis.line, ggplot2::element_blank())
  expect_equivalent(default$axis.text, ggplot2::element_blank())
  expect_equivalent(default$"axis.text.x", ggplot2::element_blank())
  expect_equivalent(default$"axis.text.y", ggplot2::element_blank())
  expect_equivalent(default$axis.ticks, ggplot2::element_blank())
  expect_equivalent(default$"axis.title.x", ggplot2::element_blank())
  expect_equivalent(default$"axis.title.y", ggplot2::element_blank())
})
