context("theme_map")
expect_is(default <- theme_map(), "theme")
expect_is(default, "gg")
expect_equivalent(default$axis.line, list())
expect_equivalent(default$axis.text, list())
expect_equivalent(default$"axis.text.x", list())
expect_equivalent(default$"axis.text.y", list())
expect_equivalent(default$axis.ticks, list())
expect_equivalent(default$"axis.title.x", list())
expect_equivalent(default$"axis.title.y", list())
